### ISSUE TITLE
Feat Request : Roles

### ISSUE THREAD

**Issue by Adrion** [initbizlab/oc-cumuluscore-plugin#16] opened 2018-09-05 13:36 UTC
What about roles for users assigned to Cluster ?

it could be a nice way to handle another permission level on modules ;

Use case example : 
 - `user1` assigned to `role1` should have access to `module1` open for every roles
 - `user2` assigned to `role2` should have access to `module2` open only for `role2`
 - `user1` assigned to `role1` shouldn't have access to `module2` open only for `role2` 

UserGroup is insufficient, a user cannot have different groups on different clusters.

**Comment by czerwonyd** [comment] 2018-09-05 15:32
To be honest we are considering building such an extension for Cumulus Core, but with a little different approach.

Right now all cluster's users has access to all cluster's modules and this is how it was designed to be. The roles in Cumulus environment should be manageable by a cluster's admin user and backend admin. As a consequence the current idea we are taking into consideration is managing roles almost like groups in `RainLab.User` so that we can decide if user can have access to a page or not based on group he/she is attached to.

Still, this is just an idea that needs to be polished very much. Right now we are working on subscriptions and payments because it is necessary for Cumulus to become complete SaaS platform.

Any ideas are very welcomed, thanks for your comments :)

**Comment by Adrion** [comment] 2018-09-07 07:09
I'm also working on Subscription system; I was considering to integrate : https://octobercms.com/plugin/offline-cashier

Yes that's what I thought, using groups like `Rainlab.User` but based on clusters.
I tried a permission system with another plugin but as I said on #15 it's not ideal.

Speaking about features, plans have limited usages. 
In my case clusters will be able to buy multiple "certifications" for website1, web2 etc. Plan isn't the best way to handle the pricing so if you're creating a subscription system you may consider to not attached it directly to a single plan. And allow more flexibility. 

It's a nice project, If you need some help... ;)

**Comment by czerwonyd** [comment] 2018-09-07 07:54
Well, contribution and this kind of help is very welcomed, thanks :)

The most recent idea of subscriptions was to have paid subscriptions to plans, so that cluster can have only one plan that it had paid for. It this case there could be a lot of plans with a variety of feature combinations. 

Can you describe your case in more detail? Why the idea does not fit your needs?

**Comment by Adrion** [comment] 2018-09-07 08:33
I agree it's a clean and simple way to use subscription; 

Imagine you create a DNS register; Users will buy one or more Domains, and subscriptions will have different deadlines and payment dates.  My use case it's pretty much the same. 
It's like having multiple "plans".

**Comment by czerwonyd** [comment] 2018-09-07 10:17
If I understand you well, managing user's domains is rather feature to be handled by a module you write rather than a core functionality.

Let's say you have user `john.smith@gmail.com` and he is assigned to `Smiths Ltd.` cluster. The cluster has access to module that manages certifications, or domains or whatsoever. In this case if you want your clients to pay you for access to this module than you can use cumulus subscriptions. For example page with `register new domain` feature or `list registered domains`. But when John wants to register new domain in your system then he have to use a different payment that concerns his domain / certificate, not his access to those pages.

**Comment by Adrion** [comment] 2018-09-07 11:40
Yes I think it's two different use cases. 

Your subscription system applied to the plan makes sense for SaaS. 

In my case I thinks that I must extend cluster and add a `many to many` relation with my `certification` model. 

I will use cumulus as a backbone but just without plans. :)

**Comment by czerwonyd** [comment] 2018-09-07 14:05
Yes, using Cumulus in such applications makes sense as well. You just have to create one plan (for example `full`) and assign all of you clusters to this plan. If your clients are registering accounts by their own than you may also configure auto assigning to assign the plan to all newly registered clusters :)

**Closed by czerwonyd** 2018-09-07 14:05 UTC
